[pytest]
testpaths = tests
filterwarnings =
    ignore:Skipping collection of '.hypothesis' directory.*:UserWarning
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:distutils Version classes are deprecated.*:DeprecationWarning:pytest_freezegun
